### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'nodeKey'

### ISSUE THREAD

**Issue by dhruvrana72** [adjoint-io/uplink-explorer#69]
I installed the uplink using source code as mentioned on this page:
[uplink-repo](https://github.com/adjoint-io/uplink).

Then, I installed uplink-explorer mentioned on this page [uplink-explorer](https://github.com/adjoint-io/uplink-explorer). I am getting this error (mentioned in title) on /accounts and /assets and when creating contract it is giving me bad request error.
I am also facing the same error in your python-sdk.
![screencapture-0-0-0-0-8000-accounts-1511349813658](https://user-images.githubusercontent.com/22045683/33125446-7f4d2d92-cfa6-11e7-8e73-0d904f8fbf14.png)

note: going by docker way, it just work fine. But if I want to go by source code, errors are there.
Machine: Intel® Core™ i5-3317U CPU @ 1.70GHz × 4 , 16 gb, OS - Ubuntu 14.04

**Comment by sdiehl** [comment]
Hi @dhruvrana72 

You'll want the stable release of the Block Explorer application. You can download it here: https://github.com/adjoint-io/uplink/releases/download/1.0/uplink-explorer.zip

**Comment by sdiehl** [comment]
Rather than building the whole stack manually, we recommend you just use the Docker image which has the entire system set up with just a single command:

```bash
$ docker run -it -p 8000:8000 --rm  uplinkdlt/uplink:latest
```

**Comment by dhruvrana72** [comment]
Hi, 
Docker image is working fine. But i wanted to work with the source code. I downloaded the stable explorer release but same error came for accounts, apparently nodeKey param was missing so I added it and working fine now.

here's the code:

```
class Account(object):
    """Account Object"""

    def __init__(self, timezone, publicKey, metadata, address, nodeKey):
        self.timezone = timezone
        self.public_key = publicKey
        self.address = address
        #added the below line
        self.nodeKey = nodeKey

        assert type(metadata) is dict

        if metadata is not None:
            self.metadata = {k: v for k, v in six.iteritems(metadata)}
        else:
            self.metadata = {}

    def __repr__(self):
        return "<Account(addr=%s)>" % self.address
```

After that while creating assets I faced a problem saying _ValueError: Cannot specify precision of Non-Fractional asset_  with precision which was precision is set to 0 for discrete  by default and we were checking for precision is not None only so I included 0 in it.



```
class AssetType(Serializable):
    """Asset Type"""

    def __init__(self, asset_type):
        asset_types = ["Fractional", "Discrete", "Binary"]
        if asset_type['type'] in asset_types:
            self.type = asset_type['type']
            if self.type == enum.AssetFractional:
                if asset_type['precision'] in [x for x in range(1, 7)]:
                    self.precision = asset_type['precision'] or None
                else:
                    self.precision = None
                    valerr = "Invalid precision for Fractional asset type."
                    raise ValueError(valerr)
            #changed the not in array added 0
            elif asset_type["precision"] not in [None, 0]:
                self.precision = None
                valerr = "Cannot specify precision of Non-Fractional asset."
                raise ValueError(valerr)
            else:
                self.precision = None
        else:
            self.type = asset_type['type']
            self.precision = None
            raise ValueError("Invalid asset type: " + asset_type['type'])
```

After this our supply was in unicode, hence 

`s = struct.pack(">Q", supply)`
was giving error. So, to fix that I changed supply to int(supply). look like this:

`s = struct.pack(">Q", int(supply))`


right now, I am getting _UnboundLocalError: local variable 'newasset_addr' referenced before assignment_ 
![screencapture-0-0-0-0-8000-assets-create-1511421917007](https://user-images.githubusercontent.com/22045683/33162473-a79896de-d04f-11e7-9881-bd99d8db0115.png)

so apparently, 


```
try:        
        result, newasset_addr = uplink.create_asset(
            private_key, from_address, name, supply, asset_type, reference, issuer, precision)
```
is not working in views.py line 244.

I am getting getting _RPCRespError_ while creating account.


```
Tx
InvalidTransaction (Transaction {header = TxAccount (CreateAccount {pubKey = "2c2615ac1837a823fca686508d5e94226900be7b591274e2f0f510aab71865ebd6f9dc69822a3cf409dfd9e4859ba26e82d641f2a24cdde3345a59b0f704b7b3", timezone = "GMT", metadata = fromList []}), signature = "AE0zNDgxOTI1NDk1NjA5OTczOTcyMTk3MTA1NzIyMTAxMjQ2MTk1ODEyMTU3MjU3OTg2ODExNzI5NzQ3MDUwNzUxMTg2NDc4NTg4NTMxMDoATjExMzk1ODAxMTMzNzgzMzA0NzA5OTQwNjI2MzE1ODgwMzE0NjU5MzU2MjYyNzQ5MTQzNTg1OTIxNTk2NzUyMDk4NzI3NDA2MzQwNjA0NQ==", origin = FuDxjQ1o2BYrhLdWCAgkjffu1Ut2kYBXdZAkYpfcNuAz, to = Nothing, timestamp = 1511422882616495}) (InvalidTxField (InvalidTxSignature (InvalidSignature (Signature {sign_r = 34819254956099739721971057221012461958121572579868117297470507511864785885310, sign_s = 113958011337833047099406263158803146593562627491435859215967520987274063406045}) "\ETX\238\NUL\128\&2c2615ac1837a823fca686508d5e94226900be7b591274e2f0f510aab71865ebd6f9dc69822a3cf409dfd9e4859ba26e82d641f2a24cdde3345a59b0f704b7b3\NUL\ETXGMT\NUL\NUL")))
```
And Assertion error while creating contracts

![screencapture-0-0-0-0-8000-contracts-create-1511422797266](https://user-images.githubusercontent.com/22045683/33162540-0a919754-d050-11e7-84a3-c4ccf338f6cc.png)



I don't want to use docker image. Your docker image works fine out of the box without any error. But I want to use the sdk.

Please look into this.

Thanks

Intel® Core™ i5-3317U CPU @ 1.70GHz × 4 , 16 gb, OS - Ubuntu 14.04

**Comment by sdiehl** [comment]
In order to manually use the block explorer against the 1.0 stable version you'll have to roll back thee block explorer SDK to use the stable version https://github.com/adjoint-io/uplink-sdk-python/commit/a74b762ebb6ac2709437698d9c41aa50edc01d9c and then `pip install` this version. 

The HEAD of block-explorer and uplink-sdk-python track the latest 1.1 release we're going to be released at the end of the month.

**Comment by dhruvrana72** [comment]
Hi,
Thank you. It worked finally.

waiting for your new stable release. 
Thanks ^_^

**Comment by sdiehl** [comment]
Lovely, let us know if you have any more issues. The 1.1 release should be out by the 29th of November. Cheers.
