### ISSUE TITLE
account not visible in drop down if we create asset from backend

### ISSUE THREAD

**Issue by dhruvrana72** [adjoint-io/uplink-explorer#73]
When I am creating a new account and asset from that account. The issuer is not visible in the drop down. 
But account is visible in accounts and block shows the transaction for asset creation.

here's the link to screencast:
https://drive.google.com/file/d/1hby_5KNyAjKOAe-3PkxuU1BZPxNdKinC/view?usp=sharing

**Comment by dtseng123** [comment]
There is a folder called "keys" where uplink-explorer is installed. The key should be dropped into that folder and named by its address and .pem. Then uplink-explorer should see this.

**Comment by sdiehl** [comment]
@dtseng123 Could you expand on how to extract the pem files from the Python SDK  for @dhruvrana72 and load it into the block explorer. IThe block explorer only can create transactions for entities it has private keys for and the SDK doesn't exchange or export private keys unless explicitly asked for, for obvious reasons.

**Comment by dtseng123** [comment]
You can export keys from the sdk this way:
```
pk, sk = ecdsa_new()
name = derive_account_address(pk)
save_key(sk, name)
```

**Comment by dtseng123** [comment]
Then after, go to the directory where it is saved. Then move the key you just saved to the keys folder in uplink-explorer.

**Comment by sdiehl** [comment]
The `Circulate` and `Transfer` transactions can also be programmatically generated from your IPython notebook session. The Block Explorer can do this for in the GUI for keys it has access to as well.

https://github.com/adjoint-io/uplink-sdk-py/blob/master/example.py#L41

**Comment by dhruvrana72** [comment]
Hello,
Sorry for late follow up. Thank you for video. It solved the issue. 
I wanted to ask one more thing. I shouldn't be posting it here. But I was not able to find the email.

So my question is there's a database mentioned [here](https://www.adjoint.io/docs/_images/arch.png)
How to access that database and see what's residing there?

**Comment by tdietert** [comment]
By default, Uplink uses LevelDB, a simple key value store using the file system. All the data is stored as bytestrings, so introspecting the leveldb data in its raw form is not doable. However, you can query the state of the database using the RPC endpoints: https://www.adjoint.io/docs/rpc.html

Before running a node, you can choose between using PostgreSQL or LevelDB by changing the `storage.backend` field in `node.config` to a valid URI. As you can see in the current `node.config` file, the URI `leveldb:///uplink` tells `uplink` to create a directory `uplink` in the current path and creates a file system database using leveldb. If you are interested in how to setup a PostgreSQL database for uplink then I will post the documentation here later today when I've finished it.

**Comment by dhruvrana72** [comment]
Sorry to bother you, yes, I am interested in learning how to setup postgresSQL db. 
Please post it here, whenever you can.
Thank You.

**Comment by tdietert** [comment]
@dhruvrana72 The documentation is now live: https://www.adjoint.io/docs/databases.html. Please let us know if you have any issues setting up uplink to work with PostgreSQL, but over on the [uplink issue tracker](https://github.com/adjoint-io/uplink/issues).
