### ISSUE TITLE
Meta data is not visible when account is created from python command line

### ISSUE THREAD

**Issue by dhruvrana72** [adjoint-io/uplink-explorer#75]
When I am creating accounts from command line with meta data it is not visible in the explorer.
command line:
![cells](https://user-images.githubusercontent.com/22045683/33868873-8f295ce2-df2b-11e7-957b-4cbb2372bd49.png)

On uplink-exploerer
![screenshot-2017-12-12 block explorer](https://user-images.githubusercontent.com/22045683/33868900-b88ad796-df2b-11e7-80f6-1fdb26370300.png)

**Comment by dtseng123** [comment]
If you pull from source and build again, it will work now.

**Comment by sdiehl** [comment]
In particular, if you pull this commit and build the block explorer the issue with the metadata being displayed should be resolved. It was just a templating issue:

https://github.com/adjoint-io/uplink-explorer/commit/290240a8514d79a2b7bd88181a1807572bfda360

**Comment by dhruvrana72** [comment]
Yes, It fixed it. 

Thank you.
