### ISSUE TITLE
How to pass multiple arguments while calling a smart contract method

### ISSUE THREAD

**Issue by dhruvrana72** [adjoint-io/uplink-explorer#83]
I have a method which takes 2 arguments, while calling it from uplink explorer, the pop up says arguments. How should I separate the arguments? Comma or space or something else?
Thank you

**Comment by sdiehl** [comment]
Hi @dhruvrana72 if your contract's method supports multiple arguments the GUI should provide you with the precise number of input fields for the argument list. 

![2018-02-05-100722_715x793_scrot](https://user-images.githubusercontent.com/236767/35799200-ea047258-0a5c-11e8-959c-4cffdfcb1619.png)

**Comment by dhruvrana72** [comment]
Hi,
I thought it the same way,but it is not showing. here the screenshot:

![screencapture-0-0-0-0-8000-contracts-45hdxhvtlvitpue5r2d6yak14swqtmkuazr4bntxr86h-1517826140375](https://user-images.githubusercontent.com/22045683/35799736-b20d0128-0a8c-11e8-86ce-896222f9ed5d.png)


here's m method:

```
@submitted
submitted(account lender, fixed4 bid_percentage) {
  if ((sender() == lender)) {
     bid = bid_percentage;
     bid_amount = (invoice_amount * ((1.0000f - bid) / 100.0000f));
     transitionTo(:bid_placed);
  };
}
```

Is there something wrong ?

**Comment by sdiehl** [comment]
Hi @dhruvrana72 we're delving into this issue, there may be something that needs to be sorted for fixed point types arguments. We'll swing back when we have answer to your query.

**Comment by sdiehl** [comment]
Hi @dhruvrana72 . Your issue should be resolved by pulling the Python SDK version `0.2.1` we pushed this morning and updating to the latest build of Uplink Explorer with PR#82 merged.

https://github.com/adjoint-io/uplink-explorer/pull/84

This should resolve your problem with fixed point arguments not appearing in the GUI.

**Comment by dhruvrana72** [comment]
I took the pull and now the parameters are showing .. but now I am not able to create new contracts. No error is thrown.
I used this script to make contract 

```
script_test = """
global int x = 0 ;
global msg invoiceNumber = "ATG_556";

transition initial -> get;
transition get -> terminal;

@get
getX () {
  terminate("Now I die.");
  return x;
}

@initial
setX () {
  x = 42;
  transitionTo(:get);
  return void;
}

"""
```

rpc interface in python returned this:

`({u'tag': u'RPCRespOK'}, '12WCpmSr9jHV7Wp79jBUsZ4NL9iyJkoT9SfrXbApigUt')`

but when I am trying to get the contract using the address returned .. It's throwing error contract not found.. 

`rpc.uplink_get_contract('12WCpmSr9jHV7Wp79jBUsZ4NL9iyJkoT9SfrXbApigUt')`

output:

`{u'tag': u'RPCRespError', u'contents': {u'errorMsg': u'Not Found: ContractDoesNotExist 12WCpmSr9jHV7Wp79jBUsZ4NL9iyJkoT9SfrXbApigUt', u'errorType': u'NotFound'}}`

**Comment by tdietert** [comment]
Can you run uplink in verbose mode (`-v` flag on command line) and paste the output? 

When the SDK submits a transaction, the uplink node just checks to see whether it is well formed or not, and does not attempt to validate the transaction any further than this as transactions often require validation in the context of a block. Your contract maybe be invalid in some unobvious way, though the transaction may be well formed. Uplink should be printing the error to console somewhere in the logs.

**Comment by dhruvrana72** [comment]
I just checked... output is this:
```

Recieved Message: 
	SendTx (SendTransactionMsg {transaction = Transaction {header = TxContract (CreateContract {address = 6Gijc4hZ6iBFgi9fuDpw5mL4S75Fn7wgxLcAtpinfwGJ, contract = "\nglobal account lender;\n        global account seller = '6UbVcaGKh2QvWUZzbXPVEHNh4ztDWumQ44SH7rigzdH2';\n        global account buyer = 'FNeAeyFC8ksRnZFRUzmWeMSMcZ8V5sMVdJ8T41o7HZFZ';\n        global msg invoice_number = \"ATH-3323-srm-3-02-2018\";\n        global fixed4 bid_percentage;\n        global int invoice_amount_ori = 17900;\n        global fixed4 invoice_amount = 17900.0000f;\n        global asset tokens_add = '2huRqK13qW2pueFE3SEkGfo5re4dDHFPMfYY8mP6ZrN7';\n        \n        \n        transition initial -> submitted;\n        transition submitted -> bid_placed;\n        transition bid_placed -> bid_accepted;\n        transition bid_accepted -> disbursed;\n        transition disbursed -> financed;\n        transition financed -> paid;\n        transition paid -> terminal;\n        \n        @initial\n        init(){\n            if((sender() == seller)){\n                transitionTo(:submitted);\n            };\n        }\n        \n        @submitted\n        submitted(account enter_lender, fixed4 bid){\n        lender = enter_lender;\n            if((sender() == lender)){\n                bid_percentage = bid;\n                bid_amount = invoice_amount * (1.0000f - bid/100.0000f);\n                transitionTo(:bid_placed);\n            };\n        }\n        \n        @bid_placed\n        bid_placed(account enter_seller){\n        seller = enter_seller;\n            if((sender() == seller)){\n                transitionTo(:bid_accepted);\n            };\n        }\n        \n        @bid_accepted\n        bid_accepted(account enter_lender){\n        lender = enter_lender;\n            if ((sender() == lender)){\n                transitionTo(:disbursed);\n            };\n        }\n        \n        @disbursed\n        disbursed(){\n            if ((sender() == seller)){\n                transferHoldings(seller, tokens_add, invoice_amount_ori, lender);\n                transitionTo(:financed);\n            };\n        }\n        @financed\n        financed(){\n            if ((sender() == buyer)){\n                transitionTo(:paid);\n            };\n        }\n        \n        \n        @paid\n        paid(account enter_lender){\n        lender = enter_lender;\n            if ((sender() == lender)){\n                transferHoldings(lender, tokens_add, invoice_amount_ori, buyer);\n                terminate(\"transaction complete\");\n            };\n        }\n"}), signature = "AE02MTM0MTMwMzMyNjA5Njg3MTYxMTAzMDMxOTQzMTI4OTgyMzU4OTY5ODcwMTQzOTE4MjA2MDA5ODQzODA3MDY4Mzg3MDExOTkzNDkzNToATTg2NzczNzQ4MjE2NDY4NjE4NTE5ODMwNjA1ODM2MzMwMDQ2OTIyNzQ5NzIzNjY5Nzg2NjczMDU3MjE5NTI1MDMzMjgxNTM2MzA0NTI3", origin = FNeAeyFC8ksRnZFRUzmWeMSMcZ8V5sMVdJ8T41o7HZFZ, timestamp = 1517911564580754}})
Adding Transaction to MemPool

```

And all the transactions are added to mem pool and visible under pending transactions tab on uplink explorer.
![screencapture-0-0-0-0-8000-transactions-pending-1517911666809](https://user-images.githubusercontent.com/22045683/35853513-b29743d4-0b53-11e8-9b3b-e51615e02481.png)

After a restart of uplink.. all of them were validated and blocks were added.
So, I guess issue is solved.

Can you give me an example, how arguments are passed in python rpc call? 

`uplink_call_contract(private_key, from_address, contract_addr, method, args)`

so for method:

```
@submitted
        submitted(account lender, fixed4 bid_percentage){
            if((sender() == lender)){
                bid_percentage = bid_percentage;
                bid_amount = invoice_amount * (1.0000f - bid_percentage/100.0000f);
                transitionTo(:bid_placed);
            };
        }
```

args are passed as `[lender_add, bid]` or `(lender_add, bid)` ?

**Comment by tdietert** [comment]
That output shows that the transaction was accepted, but what I'm really interested in is are the logs when the block was being created that included those transactions in question. It is a bit worrying that you had to restart uplink in order for the transactions to be included in a block.

As for an example contract call using the sdk:
```
    result = rpc.uplink_call_contract(private_key=alice_account.private_key,
                                      from_address=alice_account.address,
                                      contract_addr=example_contract.address,
                                      method='setX',
                                      args=[VInt(42)])
```
The arguments should be passed as a list of values, using the `V[..]` constructors found in the `uplink/protocol.py` file, correspoding to the type of the method argument in that position. For instance:
```
submitted(account lender, fixed4 bid_percentage)
```
should be called with the arguments
```
uplink_call_contract(..., args = [VAccount(<AccountAddress>), VFixed (Decimal("3.22"),2)])
```

**Comment by tdietert** [comment]
We are currently working on better SDK documentation, so please bear with us.

**Comment by sdiehl** [comment]
Following up, has this issue been resolved?

**Comment by dhruvrana72** [comment]
Yeah, sorry. I thought, I closed the issue. 
Thanks for help.
